### ISSUE TITLE
Predefined Responses

### ISSUE THREAD

**Issue by vizvaryt** [jharaneda/Trikaja#11]
As an agent, I want to click on a button where I can select different predefined responses that are added to the comment section where the answer to the ticket will be, so I can save time and not have spelling mistakes.

**Comment by jharaneda** [comment]
- [ ] Create answer model
- [ ] Create answer DAO
- [ ] Create answer Row mapper
- [ ] Create answer view
- [ ] Create answer list
- [ ] Create answer SQL Schema
- [ ] Create answer SQL Data

**Comment by jharaneda** [comment]
Added select that when is clicked it will add info into the comment input. This feature is closed.
