### ISSUE TITLE
Ticket Management

### ISSUE THREAD

**Issue by vizvaryt** [jharaneda/Trikaja#5]
As a user, I want to be able to create new tickets, and update any tickets I have made in the past that are yet to be resolved.
As an agent, I want to be able to create new tickets, update their status, and update their information in relevance to the end user who created the ticket originally.
As a manager, I want to be able to create new tickets, update and change all information related to a ticket, and delete tickets.

**Comment by jharaneda** [comment]
User was added when ticket is created. Now the ticket is created with the correct user that is logged into the app.
