### ISSUE TITLE
Login/Logout

### ISSUE THREAD

**Issue by vizvaryt** [jharaneda/Trikaja#7]
As a user I want to login/logout of the application whenever I want, access my profile, and watch my tickets.

**Comment by jharaneda** [comment]
Starting to analyze different scenarios about session.

- we can develop adding a new attribute to the user classes
- or we can develop adding a session model with its own attributes

**Comment by jharaneda** [comment]
After some testing we will use a model class and dao to manage sessions.

**Comment by jharaneda** [comment]
Tasks

- [ ] Session Schema 
- [ ] Session Model
- [ ] Session Row mapper
- [ ] Session DAO

**Comment by jharaneda** [comment]
We started testing login, authentication control of each URL.

**Comment by jharaneda** [comment]
Testing done. The user can login and the user will see diferent views depending on the user role/position.
